//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//!  \file       CvEnums.h
//!  \brief     Public header common Civ5 enumerations
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#pragma once
#ifndef CVENUMS_H
#define CVENUMS_H

// If you want the game to work correctly, be careful when you modify ButtonPopupTypes.
// They are directly tied into playing sounds, so if you add, remove, or (God forbid) replace one of these,
// please make sure if you want a sound to play, modify Assets\\Sounds\\ButtonPopupSounds.xml.  You also need to
// modify cvAudioSimMainGame::BuildButtonPopupSoundTable to register the link between the enum and the sound ID (the text hash of the enum name).

enum ButtonPopupTypes
{
	BUTTONPOPUP_TEXT,
	BUTTONPOPUP_MAIN_MENU,
	BUTTONPOPUP_CONFIRM_MENU,
	BUTTONPOPUP_DECLAREWARMOVE,
	BUTTONPOPUP_DECLAREWARRANGESTRIKE,
	BUTTONPOPUP_CONFIRMCOMMAND,
	BUTTONPOPUP_CONFIRM_CITY_TASK,
	BUTTONPOPUP_CONFIRM_IMPROVEMENT_BUILD,
	BUTTONPOPUP_GREAT_PERSON,
	BUTTONPOPUP_LOADUNIT,
	BUTTONPOPUP_LEADUNIT,
	BUTTONPOPUP_CHOOSETECH,
	BUTTONPOPUP_CITY_CAPTURED,
	BUTTONPOPUP_ANNEX_CITY,
	BUTTONPOPUP_STATION,
	BUTTONPOPUP_ATTACK_SITE,
	BUTTONPOPUP_OUTPOST,
	BUTTONPOPUP_DISBANDCITY,
	BUTTONPOPUP_CHOOSEPRODUCTION,
	BUTTONPOPUP_CHOOSEPOLICY,
	BUTTONPOPUP_CHOOSECITYPURCHASE,
	BUTTONPOPUP_CHOOSEELECTION,
	BUTTONPOPUP_DIPLOVOTE,
	BUTTONPOPUP_ALARM,
	BUTTONPOPUP_DEAL_CANCELED,
	BUTTONPOPUP_PYTHON,
	BUTTONPOPUP_PYTHON_SCREEN,
	BUTTONPOPUP_DETAILS,
	BUTTONPOPUP_ADMIN,
	BUTTONPOPUP_ADMIN_PASSWORD,
	BUTTONPOPUP_EXTENDED_GAME,
	BUTTONPOPUP_DIPLOMACY,
	BUTTONPOPUP_ADDBUDDY,
	BUTTONPOPUP_FORCED_DISCONNECT,
	BUTTONPOPUP_PITBOSS_DISCONNECT,
	BUTTONPOPUP_KICKED,
	BUTTONPOPUP_RETIRE,
	BUTTONPOPUP_FREE_COLONY,
	BUTTONPOPUP_LAUNCH,
	BUTTONPOPUP_MINOR_GOLD,
	BUTTONPOPUP_MINOR_CIV_QUEST,
	BUTTONPOPUP_MINOR_CIV_QUEST_COMPLETED,
	BUTTONPOPUP_MINOR_CIV_INTRUSION,
	BUTTONPOPUP_MINOR_CIV_GREETING_AND_WAR,
	BUTTONPOPUP_BARBARIAN_RANSOM,
	BUTTONPOPUP_MINOR_CIV_ENTER_TERRITORY,
	BUTTONPOPUP_TEMP_SPECIALISTS,
	BUTTONPOPUP_NOTIFICATION_LOG,
	BUTTONPOPUP_ECONOMIC_OVERVIEW,
	BUTTONPOPUP_MILITARY_OVERVIEW,
	BUTTONPOPUP_DIPLOMATIC_OVERVIEW,
	BUTTONPOPUP_DEMOGRAPHICS,
	BUTTONPOPUP_VICTORY_INFO,
	BUTTONPOPUP_MINOR_CIVS_LIST,
	BUTTONPOPUP_GIFT_CONFIRM,
	BUTTONPOPUP_RETURN_CIVILIAN,
	BUTTONPOPUP_CONFIRM_POLICY_BRANCH_SWITCH,
	BUTTONPOPUP_WHOS_WINNING,
	BUTTONPOPUP_NEW_ERA,
	BUTTONPOPUP_GOODY_HUT_REWARD,
	BUTTONPOPUP_BARBARIAN_CAMP_REWARD,
	BUTTONPOPUP_ERA_OF_PROSPERITY_REWARD,
	BUTTONPOPUP_GREAT_PERSON_REWARD,
	BUTTONPOPUP_CITY_STATE_GREETING,
	BUTTONPOPUP_CITY_STATE_MESSAGE,
	BUTTONPOPUP_CITY_STATE_DIPLO,
	BUTTONPOPUP_CITY_PLOT_MANAGEMENT,
	BUTTONPOPUP_DIPLO_VOTE,
	BUTTONPOPUP_VOTE_RESULTS,
	BUTTONPOPUP_TECH_TREE,
	BUTTONPOPUP_TECH_AWARD,
	BUTTONPOPUP_WONDER_COMPLETED_ACTIVE_PLAYER,
	BUTTONPOPUP_ADVISOR_INFO,
	BUTTONPOPUP_ADVISOR_COUNSEL,
	BUTTONPOPUP_ADVISOR_MODAL,
	BUTTONPOPUP_RENAME_CITY,
	BUTTONPOPUP_RENAME_UNIT,
	BUTTONPOPUP_CHOOSE_FREE_GREAT_PERSON,
	BUTTONPOPUP_FOUND_PANTHEON,
	BUTTONPOPUP_FOUND_RELIGION,
	BUTTONPOPUP_ESPIONAGE_OVERVIEW,
	BUTTONPOPUP_RELIGION_OVERVIEW,
	BUTTONPOPUP_CHOOSE_TECH_TO_STEAL,
	BUTTONPOPUP_CHOOSE_FAITH_GREAT_PERSON,

	// Do not add any more sequential enums!  Use hash values!

	BUTTONPOPUP_MODDER_0,
	BUTTONPOPUP_MODDER_1,
	BUTTONPOPUP_MODDER_2,
	BUTTONPOPUP_MODDER_3,
	BUTTONPOPUP_MODDER_4,
	BUTTONPOPUP_MODDER_5,
	BUTTONPOPUP_MODDER_6,
	BUTTONPOPUP_MODDER_7,
	BUTTONPOPUP_MODDER_8,
	BUTTONPOPUP_MODDER_9,
	BUTTONPOPUP_MODDER_10,
	BUTTONPOPUP_MODDER_11,

	NUM_FIXED_BUTTONPOPUP_TYPES,
};

// Mem Allocation Tags
enum eCiv5GameCoreMPoolType
{
	c_eCiv5GameplayDLL = 0x4e8,
};

enum GoodyTypes
{
	NO_GOODY = -1,
};

enum PlayerTypes
{
	NO_PLAYER = -1,
};

enum ProjectTypes
{
	NO_PROJECT = -1,
};

enum FlavorTypes
{
	NO_FLAVOR = -1,
};

enum ActionSubTypes
{
	NO_ACTIONSUBTYPE = -1,
	ACTIONSUBTYPE_INTERFACEMODE,
	ACTIONSUBTYPE_COMMAND,
	ACTIONSUBTYPE_BUILD,
	ACTIONSUBTYPE_PROMOTION,
	ACTIONSUBTYPE_SPECIALIST,
	ACTIONSUBTYPE_CONTROL,
	ACTIONSUBTYPE_AUTOMATE,
	ACTIONSUBTYPE_MISSION,
	NUM_ACTIONSUBTYPES
};

enum ReplayMessageTypes
{
	NO_REPLAY_MESSAGE = -1,

	REPLAY_MESSAGE_MAJOR_EVENT,
	REPLAY_MESSAGE_CITY_FOUNDED,
	REPLAY_MESSAGE_PLOT_OWNER_CHANGE,
	REPLAY_MESSAGE_CITY_CAPTURED,
	REPLAY_MESSAGE_CITY_DESTROYED,
	REPLAY_MESSAGE_RELIGION_FOUNDED,
	REPLAY_MESSAGE_PANTHEON_FOUNDED,

	NUM_REPLAY_MESSAGE_TYPES
};

enum TechTypes
{
	NO_TECH = -1,
};

#endif // CVENUMS_H