//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//!  \file       CvEnums.h
//!  \brief     Public header common Civ5 enumerations
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#pragma once

// SDK archaeology types retained in Beyond Earth's native plot layout.
enum GreatWorkArtifactClass { NO_GREAT_WORK_ARTIFACT_CLASS = 0 };
enum GreatWorkType { NO_GREAT_WORK = -1 };
#ifndef CVENUMS_H
#define CVENUMS_H

// If you want the game to work correctly, be careful when you modify ButtonPopupTypes.
// They are directly tied into playing sounds, so if you add, remove, or (God forbid) replace one of these,
// please make sure if you want a sound to play, modify Assets\\Sounds\\ButtonPopupSounds.xml.  You also need to
// modify cvAudioSimMainGame::BuildButtonPopupSoundTable to register the link between the enum and the sound ID (the text hash of the enum name).

enum ButtonPopupTypes
{
	BUTTONPOPUP_TEXT,
	BUTTONPOPUP_MAIN_MENU,
	BUTTONPOPUP_CONFIRM_MENU,
	BUTTONPOPUP_DECLAREWARMOVE,
	BUTTONPOPUP_DECLAREWARRANGESTRIKE,
	BUTTONPOPUP_CONFIRMCOMMAND,
	BUTTONPOPUP_CONFIRM_CITY_TASK,
	BUTTONPOPUP_CONFIRM_IMPROVEMENT_BUILD,
	BUTTONPOPUP_GREAT_PERSON,
	BUTTONPOPUP_LOADUNIT,
	BUTTONPOPUP_LEADUNIT,
	BUTTONPOPUP_CHOOSETECH,
	BUTTONPOPUP_CITY_CAPTURED,
	BUTTONPOPUP_ANNEX_CITY,
	BUTTONPOPUP_STATION,
	BUTTONPOPUP_ATTACK_SITE,
	BUTTONPOPUP_OUTPOST,
	BUTTONPOPUP_DISBANDCITY,
	BUTTONPOPUP_CHOOSEPRODUCTION,
	BUTTONPOPUP_CHOOSEPOLICY,
	BUTTONPOPUP_CHOOSECITYPURCHASE,
	BUTTONPOPUP_CHOOSEELECTION,
	BUTTONPOPUP_DIPLOVOTE,
	BUTTONPOPUP_ALARM,
	BUTTONPOPUP_DEAL_CANCELED,
	BUTTONPOPUP_PYTHON,
	BUTTONPOPUP_PYTHON_SCREEN,
	BUTTONPOPUP_DETAILS,
	BUTTONPOPUP_ADMIN,
	BUTTONPOPUP_ADMIN_PASSWORD,
	BUTTONPOPUP_EXTENDED_GAME,
	BUTTONPOPUP_DIPLOMACY,
	BUTTONPOPUP_ADDBUDDY,
	BUTTONPOPUP_FORCED_DISCONNECT,
	BUTTONPOPUP_PITBOSS_DISCONNECT,
	BUTTONPOPUP_KICKED,
	BUTTONPOPUP_RETIRE,
	BUTTONPOPUP_FREE_COLONY,
	BUTTONPOPUP_LAUNCH,
	BUTTONPOPUP_MINOR_GOLD,
	BUTTONPOPUP_MINOR_CIV_QUEST,
	BUTTONPOPUP_MINOR_CIV_QUEST_COMPLETED,
	BUTTONPOPUP_MINOR_CIV_INTRUSION,
	BUTTONPOPUP_MINOR_CIV_GREETING_AND_WAR,
	BUTTONPOPUP_BARBARIAN_RANSOM,
	BUTTONPOPUP_MINOR_CIV_ENTER_TERRITORY,
	BUTTONPOPUP_TEMP_SPECIALISTS,
	BUTTONPOPUP_NOTIFICATION_LOG,
	BUTTONPOPUP_ECONOMIC_OVERVIEW,
	BUTTONPOPUP_MILITARY_OVERVIEW,
	BUTTONPOPUP_DIPLOMATIC_OVERVIEW,
	BUTTONPOPUP_DEMOGRAPHICS,
	BUTTONPOPUP_VICTORY_INFO,
	BUTTONPOPUP_MINOR_CIVS_LIST,
	BUTTONPOPUP_GIFT_CONFIRM,
	BUTTONPOPUP_RETURN_CIVILIAN,
	BUTTONPOPUP_CONFIRM_POLICY_BRANCH_SWITCH,
	BUTTONPOPUP_WHOS_WINNING,
	BUTTONPOPUP_NEW_ERA,
	BUTTONPOPUP_GOODY_HUT_REWARD,
	BUTTONPOPUP_BARBARIAN_CAMP_REWARD,
	BUTTONPOPUP_ERA_OF_PROSPERITY_REWARD,
	BUTTONPOPUP_GREAT_PERSON_REWARD,
	BUTTONPOPUP_CITY_STATE_GREETING,
	BUTTONPOPUP_CITY_STATE_MESSAGE,
	BUTTONPOPUP_CITY_STATE_DIPLO,
	BUTTONPOPUP_CITY_PLOT_MANAGEMENT,
	BUTTONPOPUP_DIPLO_VOTE,
	BUTTONPOPUP_VOTE_RESULTS,
	BUTTONPOPUP_TECH_TREE,
	BUTTONPOPUP_TECH_AWARD,
	BUTTONPOPUP_WONDER_COMPLETED_ACTIVE_PLAYER,
	BUTTONPOPUP_ADVISOR_INFO,
	BUTTONPOPUP_ADVISOR_COUNSEL,
	BUTTONPOPUP_ADVISOR_MODAL,
	BUTTONPOPUP_RENAME_CITY,
	BUTTONPOPUP_RENAME_UNIT,
	BUTTONPOPUP_CHOOSE_FREE_GREAT_PERSON,
	BUTTONPOPUP_FOUND_PANTHEON,
	BUTTONPOPUP_FOUND_RELIGION,
	BUTTONPOPUP_ESPIONAGE_OVERVIEW,
	BUTTONPOPUP_RELIGION_OVERVIEW,
	BUTTONPOPUP_CHOOSE_TECH_TO_STEAL,
	BUTTONPOPUP_CHOOSE_FAITH_GREAT_PERSON,

	// Do not add any more sequential enums!  Use hash values!

	BUTTONPOPUP_MODDER_0,
	BUTTONPOPUP_MODDER_1,
	BUTTONPOPUP_MODDER_2,
	BUTTONPOPUP_MODDER_3,
	BUTTONPOPUP_MODDER_4,
	BUTTONPOPUP_MODDER_5,
	BUTTONPOPUP_MODDER_6,
	BUTTONPOPUP_MODDER_7,
	BUTTONPOPUP_MODDER_8,
	BUTTONPOPUP_MODDER_9,
	BUTTONPOPUP_MODDER_10,
	BUTTONPOPUP_MODDER_11,

	NUM_FIXED_BUTTONPOPUP_TYPES,
};

// Mem Allocation Tags
enum eCiv5GameCoreMPoolType
{
	c_eCiv5GameplayDLL = 0x4e8,
};

enum GoodyTypes
{
	NO_GOODY = -1,
};

enum PlayerTypes
{
	NO_PLAYER = -1,
};

enum ProjectTypes
{
	NO_PROJECT = -1,
};

enum VictoryTypes
{
	NO_VICTORY = -1
};

// Beyond Earth's affinity identifiers are data-driven.
enum AffinityType
{
	NO_AFFINITY_TYPE = -1
};

enum AdvancedStartActionTypes
{
	NO_ADVANCEDSTARTACTION = -1,
	ADVANCEDSTARTACTION_EXIT,
	ADVANCEDSTARTACTION_UNIT,
	ADVANCEDSTARTACTION_CITY,
	ADVANCEDSTARTACTION_POP,
	ADVANCEDSTARTACTION_CULTURE,
	ADVANCEDSTARTACTION_BUILDING,
	ADVANCEDSTARTACTION_IMPROVEMENT,
	ADVANCEDSTARTACTION_ROUTE,
	ADVANCEDSTARTACTION_TECH,
	ADVANCEDSTARTACTION_VISIBILITY,
	ADVANCEDSTARTACTION_AUTOMATE,
	NUM_ADVANCEDSTARTACTIONS
};

enum BeliefTypes
{
	NO_BELIEF = -1
};

enum BuildingClassTypes
{
	NO_BUILDINGCLASS = -1
};

enum BuildingTypes
{
	NO_BUILDING = -1
};

enum CargoTypes
{
	RANDOM_CARGO = -2,
	NO_SELECTED_CARGO
};

enum ChatTargetTypes
{
	NO_CHATTARGET = -1,
	CHATTARGET_ALL = -2,
	CHATTARGET_TEAM = -3,
	CHATTARGET_PLAYER = -4
};

enum CityAIFocusTypes
{
	NO_CITY_AI_FOCUS_TYPE = -1,
	CITY_AI_FOCUS_TYPE_FOOD,
	CITY_AI_FOCUS_TYPE_PRODUCTION,
	CITY_AI_FOCUS_TYPE_ENERGY,
	CITY_AI_FOCUS_TYPE_GREAT_PEOPLE,
	CITY_AI_FOCUS_TYPE_SCIENCE,
	CITY_AI_FOCUS_TYPE_CULTURE,
	CITY_AI_FOCUS_TYPE_PROD_GROWTH,
	CITY_AI_FOCUS_TYPE_ENERGY_GROWTH,
	CITY_AI_FOCUS_TYPE_FAITH,
	NUM_CITY_AI_FOCUS_TYPES
};

enum ColonistTypes
{
	RANDOM_COLONIST = -2,
	NO_SELECTED_COLONIST
};

enum CommandTypes
{
	NO_COMMAND = -1,
	COMMAND_PROMOTION,
	COMMAND_UPGRADE,
	COMMAND_AUTOMATE,
	COMMAND_WAKE,
	COMMAND_CANCEL,
	COMMAND_CANCEL_ALL,
	COMMAND_STOP_AUTOMATION,
	COMMAND_DELETE,
	COMMAND_GIFT,
	COMMAND_HOTKEY,
	NUM_COMMAND_TYPES
};

enum DiploUIStateTypes
{
	NO_DIPLO_UI_STATE = -1,
	DIPLO_UI_STATE_DEFAULT_ROOT,
	DIPLO_UI_STATE_WAR_DECLARED_BY_HUMAN,
	DIPLO_UI_STATE_PEACE_MADE_BY_HUMAN,
	DIPLO_UI_STATE_TRADE,
	DIPLO_UI_STATE_TRADE_AI_MAKES_OFFER,
	DIPLO_UI_STATE_TRADE_AI_ACCEPTS_OFFER,
	DIPLO_UI_STATE_TRADE_AI_REJECTS_OFFER,
	DIPLO_UI_STATE_TRADE_AI_MAKES_DEMAND,
	DIPLO_UI_STATE_TRADE_AI_MAKES_REQUEST,
	DIPLO_UI_STATE_TRADE_HUMAN_OFFERS_CONCESSIONS,
	DIPLO_UI_STATE_HUMAN_DEMAND,
	DIPLO_UI_STATE_BLANK_DISCUSSION_RETURN_TO_ROOT,
	DIPLO_UI_STATE_BLANK_DISCUSSION,
	DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_HUMAN,
	DIPLO_UI_STATE_BLANK_DISCUSSION_MEAN_AI,
	DIPLO_UI_STATE_AI_DECLARED_WAR,
	DIPLO_UI_STATE_DISCUSS_HUMAN_INVOKED,
	DIPLO_UI_STATE_DISCUSS_AGGRESSIVE_MILITARY_WARNING,
	DIPLO_UI_STATE_DISCUSS_YOU_EXPANSION_SERIOUS_WARNING,
	DIPLO_UI_STATE_DISCUSS_YOU_EXPANSION_WARNING,
	DIPLO_UI_STATE_DISCUSS_YOU_PLOT_BUYING_SERIOUS_WARNING,
	DIPLO_UI_STATE_DISCUSS_YOU_PLOT_BUYING_WARNING,
	DIPLO_UI_STATE_DISCUSS_WORK_WITH_US,
	DIPLO_UI_STATE_DISCUSS_WORK_AGAINST_SOMEONE,
	DIPLO_UI_STATE_DISCUSS_COOP_WAR,
	DIPLO_UI_STATE_DISCUSS_COOP_WAR_TIME,
	DIPLO_UI_STATE_DISCUSS_PLAN_RESEARCH_AGREEMENT,
	DIPLO_UI_STATE_DISCUSS_AI_REQUEST_DENOUNCE,
	DIPLO_UI_STATE_CAUGHT_YOUR_SPY,
	DIPLO_UI_STATE_KILLED_YOUR_SPY,
	DIPLO_UI_STATE_KILLED_MY_SPY,
	DIPLO_UI_STATE_CONFRONT_YOU_KILLED_MY_SPY,
	DIPLO_UI_STATE_COVERT_OPS_BOMBSHELL,
	DIPLO_UI_STATE_STOP_DIGGING,
	DIPLO_UI_STATE_WARN_SPREAD_MIASMA,
	DIPLO_UI_STATE_WARN_REMOVE_MIASMA,
	DIPLO_UI_STATE_WARN_ANTAGONIZE_ALIENS,
	DIPLO_UI_STATE_WARN_ORBITAL_DEPLOYMENT,
	DIPLO_UI_STATE_WARN_STATION_AGGRESSION,
	NUM_DIPLO_UI_STATES
};

enum EAchievement
{
	ACHIEVEMENT_WIN_HUTAMA,
	ACHIEVEMENT_WIN_DAOMING,
	ACHIEVEMENT_WIN_FIELDING,
	ACHIEVEMENT_WIN_KOZLOV,
	ACHIEVEMENT_WIN_BARRE,
	ACHIEVEMENT_WIN_ELODIE,
	ACHIEVEMENT_WIN_BOLIVAR,
	ACHIEVEMENT_WIN_KAVITHA,
	ACHIEVEMENT_WIN_ALLBASELEADERS,
	ACHIEVEMENT_DIFLEVEL_SPUTNIK,
	ACHIEVEMENT_DIFLEVEL_MERCURY,
	ACHIEVEMENT_DIFLEVEL_VOSTOK,
	ACHIEVEMENT_DIFLEVEL_GEMINI,
	ACHIEVEMENT_DIFLEVEL_SOYUZ,
	ACHIEVEMENT_DIFLEVEL_APOLLO,
	ACHIEVEMENT_VICTORY_DOMINATION,
	ACHIEVEMENT_VICTORY_CONTACT,
	ACHIEVEMENT_VICTORY_PROMISED_LAND,
	ACHIEVEMENT_VICTORY_EMANCIPATION,
	ACHIEVEMENT_VICTORY_TRANSCENDENCE,
	ACHIEVEMENT_VICTORY_ALL,
	ACHIEVEMENT_MAPSIZE_DUEL,
	ACHIEVEMENT_MAPSIZE_TINY,
	ACHIEVEMENT_MAPSIZE_SMALL,
	ACHIEVEMENT_MAPSIZE_STANDARD,
	ACHIEVEMENT_MAPSIZE_LARGE,
	ACHIEVEMENT_MAPTYPE_ARCHIPELAGO,
	ACHIEVEMENT_MAPTYPE_ATLANTEAN,
	ACHIEVEMENT_MAPTYPE_EQUATORIAL,
	ACHIEVEMENT_MAPTYPE_PROTEAN,
	ACHIEVEMENT_MAPTYPE_SKIRMISH,
	ACHIEVEMENT_MAPTYPE_TAIGAN,
	ACHIEVEMENT_MAPTYPE_TERRAN,
	ACHIEVEMENT_MAPS_ALL,
	ACHIEVEMENT_ANY_WONDER,
	ACHIEVEMENT_ALL_WONDERS,
	ACHIEVEMENT_CITY_100CULTURE,
	ACHIEVEMENT_CITY_100ENERGY,
	ACHIEVEMENT_CITY_100SCIENCE,
	ACHIEVEMENT_UNIT_UPGRADED,
	ACHIEVEMENT_ONEHITKILL,
	ACHIEVEMENT_RAZE_ALIEN_NESTS,
	ACHIEVEMENT_UNIT_EMBARK,
	ACHIEVEMENT_ALL_TECHS,
	ACHIEVEMENT_POLICY_MIGHT,
	ACHIEVEMENT_POLICY_PROSPERITY,
	ACHIEVEMENT_POLICY_KNOWLEDGE,
	ACHIEVEMENT_POLICY_INDUSTRY,
	ACHIEVEMENT_KILL_SPY,
	ACHIEVEMENT_STOLEN_TECH,
	ACHIEVEMENT_WIN_MULTIPLAYER,
	ACHIEVEMENT_PLAY_MOD,
	ACHIEVEMENT_MOD_DOWNLOADED,
	ACHIEVEMENT_PURCHASE_TILES,
	ACHIEVEMENT_SUCK_AT_WONDERS,
	ACHIEVEMENT_ALIENS_KILLED,
	ACHIEVEMENT_KILLED_SIEGE_WORM,
	ACHIEVEMENT_ORBITAL_UNIT_LAUNCHED,
	ACHIEVEMENT_VIRTUES_TIER1KICKERS,
	ACHIEVEMENT_VIRTUES_TIER2KICKERS,
	ACHIEVEMENT_VIRTUES_TIER3KICKERS,
	ACHIEVEMENT_AFFINITY_MAXHARMONY,
	ACHIEVEMENT_AFFINITY_MAXPURITY,
	ACHIEVEMENT_AFFINITY_MAXSUPREMACY,
	ACHIEVEMENT_XP1_1,
	ACHIEVEMENT_XP1_2,
	ACHIEVEMENT_XP1_3,
	ACHIEVEMENT_XP1_4,
	ACHIEVEMENT_XP1_5,
	ACHIEVEMENT_XP1_6,
	ACHIEVEMENT_XP1_7,
	ACHIEVEMENT_XP1_8,
	ACHIEVEMENT_XP1_9,
	ACHIEVEMENT_XP1_10,
	ACHIEVEMENT_XP1_11,
	ACHIEVEMENT_XP1_12,
	ACHIEVEMENT_XP1_13,
	ACHIEVEMENT_XP1_14,
	ACHIEVEMENT_XP1_15,
	ACHIEVEMENT_XP1_16,
	ACHIEVEMENT_XP1_17,
	ACHIEVEMENT_XP1_18,
	ACHIEVEMENT_XP1_19,
	ACHIEVEMENT_XP1_20,
	ACHIEVEMENT_XP1_21,
	ACHIEVEMENT_XP1_22,
	ACHIEVEMENT_XP1_23,
	ACHIEVEMENT_XP1_24,
	ACHIEVEMENT_XP1_25,
	ACHIEVEMENT_XP1_26,
	NUM_ACHIEVEMENTS
};

enum ESteamStat
{
	ESTEAMSTAT_TOTAL_WINS,
	ESTEAMSTAT_WONDERS_START,
	ESTEAMSTAT_GENE_VAULT = 1,
	ESTEAMSTAT_STELLAR_CODEX,
	ESTEAMSTAT_MASTER_CONTROL,
	ESTEAMSTAT_PANOPTICON,
	ESTEAMSTAT_ECTOGENESIS_POD,
	ESTEAMSTAT_PRECOG_PROJECT,
	ESTEAMSTAT_MEMETWORK,
	ESTEAMSTAT_CRAWLER,
	ESTEAMSTAT_MASS_DRIVER,
	ESTEAMSTAT_DRONE_SPHERE,
	ESTEAMSTAT_NEW_TERRAN_MYTH,
	ESTEAMSTAT_HUMAN_HIVE,
	ESTEAMSTAT_XENODROME,
	ESTEAMSTAT_HOLON_CHAMBER,
	ESTEAMSTAT_ARCHIMEDES_LEVER,
	ESTEAMSTAT_MARKOV_ECLIPSE,
	ESTEAMSTAT_PROMETHEAN,
	ESTEAMSTAT_TECTONIC_ANVIL,
	ESTEAMSTAT_QUANTUM_COMPUTER,
	ESTEAMSTAT_NANOTHERMITE,
	ESTEAMSTAT_ARMASAIL,
	ESTEAMSTAT_XENOMALLEUM,
	ESTEAMSTAT_XENONOVA,
	ESTEAMSTAT_RESURRECTION_DEVICE,
	ESTEAMSTAT_DEEP_MEMORY,
	ESTEAMSTAT_ANSIBLE,
	ESTEAMSTAT_BYTEGEIST,
	ESTEAMSTAT_CYNOSURE,
	ESTEAMSTAT_DAEDALUS_LADDER,
	ESTEAMSTAT_BASE_WONDERS_END = 29,
	ESTEAMSTAT_AKKOROKAMUI,
	ESTEAMSTAT_FARADAY_GYRE,
	ESTEAMSTAT_BENTHIC_AUGER,
	ESTEAMSTAT_EUPHOTIC_STRAND,
	ESTEAMSTAT_GUO_PU_YAOLAN,
	ESTEAMSTAT_ABYSSAL_MIRROR,
	ESTEAMSTAT_MACHINE_ASSISTED_FREE_WILL,
	ESTEAMSTAT_DIMENSION_FOLDING_COMPLEX,
	ESTEAMSTAT_QUANTUM_POLITICS,
	ESTEAMSTAT_TESSELATION_FOUNDRY,
	ESTEAMSTAT_TEMPORAL_CALCULUS,
	ESTEAMSTAT_RELATIVISTIC_DATA_BANK,
	ESTEAMSTAT_WONDERS_END,
	ESTEAMSTAT_RAZE_ALIEN_NEST = 42,
	ESTEAMSTAT_TILESPURCHASED,
	ESTEAMSTAT_BEATWONDERS,
	ESTEAMSTAT_ALIENS_KILLED,
	ESTEAMSTAT_CITY_MOVES,
	ESTEAMSTAT_ARTIFACTS_FOUND,
	ESTEAMSTAT_USED_ALIEN_ARTIFACTS,
	ESTEAMSTAT_USED_EARTH_ARTIFACTS,
	ESTEAMSTAT_USED_PROGENITOR_ARTIFACTS,
	ESTEAMSTAT_INVISIBLE_KILLS,
	ESTEAMSTAT_MARVEL_QUEST_LUSH,
	ESTEAMSTAT_MARVEL_QUEST_ARID,
	ESTEAMSTAT_MARVEL_QUEST_FUNGAL,
	ESTEAMSTAT_MARVEL_QUEST_PRIMORDIAL,
	ESTEAMSTAT_MARVEL_QUEST_FRIGID,
	ESTEAMSTAT_MARVEL_QUEST_WATER,
	ESTEAMSTAT_MARVEL_QUESTS_END = 57,
	NUM_STEAM_STATS
};

enum FaithPurchaseTypes
{
	NO_AUTOMATIC_FAITH_PURCHASE,
	FAITH_PURCHASE_SAVE_PROPHET,
	FAITH_PURCHASE_BUILDING,
	FAITH_PURCHASE_UNIT
};

enum ForeignPolicyTypes
{
	NO_FOREIGN_POLICY = -1
};

enum FromUIDiploEventTypes
{
	NO_FROM_UI_DIPLO_EVENT = -1,
	FROM_UI_DIPLO_EVENT_HUMAN_DECLARES_WAR,
	FROM_UI_DIPLO_EVENT_HUMAN_NEGOTIATE_PEACE,
	FROM_UI_DIPLO_EVENT_HUMAN_WANTS_DISCUSSION,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_DONT_SETTLE,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_WORK_WITH_US,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_END_WORK_WITH_US,
	FROM_UI_DIPLO_EVENT_DEMAND_HUMAN_REFUSAL,
	FROM_UI_DIPLO_EVENT_REQUEST_HUMAN_REFUSAL,
	FROM_UI_DIPLO_EVENT_AGGRESSIVE_MILITARY_WARNING_RESPONSE,
	FROM_UI_DIPLO_EVENT_EXPANSION_SERIOUS_WARNING_RESPONSE,
	FROM_UI_DIPLO_EVENT_EXPANSION_WARNING_RESPONSE,
	FROM_UI_DIPLO_EVENT_PLOT_BUYING_SERIOUS_WARNING_RESPONSE,
	FROM_UI_DIPLO_EVENT_PLOT_BUYING_WARNING_RESPONSE,
	FROM_UI_DIPLO_EVENT_WORK_WITH_US_RESPONSE,
	FROM_UI_DIPLO_EVENT_WORK_AGAINST_SOMEONE_RESPONSE,
	FROM_UI_DIPLO_EVENT_DENOUNCE,
	FROM_UI_DIPLO_EVENT_COOP_WAR_OFFER,
	FROM_UI_DIPLO_EVENT_COOP_WAR_RESPONSE,
	FROM_UI_DIPLO_EVENT_COOP_WAR_NOW_RESPONSE,
	FROM_UI_DIPLO_EVENT_HUMAN_DEMAND,
	FROM_UI_DIPLO_EVENT_PLAN_RA_RESPONSE,
	FROM_UI_DIPLO_EVENT_AI_REQUEST_DENOUNCE_RESPONSE,
	FROM_UI_DIPLO_EVENT_CAUGHT_YOUR_SPY_RESPONSE,
	FROM_UI_DIPLO_EVENT_KILLED_MY_SPY_RESPONSE,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_STOP_SPYING,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_STOP_DIGGING,
	FROM_UI_DIPLO_EVENT_STOP_DIGGING,
	FROM_UI_DIPLO_EVENT_WARN_SPREAD_MIASMA,
	FROM_UI_DIPLO_EVENT_WARN_REMOVE_MIASMA,
	FROM_UI_DIPLO_EVENT_WARN_ANTAGONIZE_ALIENS,
	FROM_UI_DIPLO_EVENT_WARN_ORBITAL_DEPLOYMENT,
	FROM_UI_DIPLO_EVENT_WARN_STATION_AGGRESSION,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_STOP_ANTAGONIZE_ALIENS,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_STOP_ORBITAL_DEPLOYMENT,
	FROM_UI_DIPLO_EVENT_HUMAN_DISCUSSION_STOP_STATION_AGGRESSION,
	NUM_FROM_UI_DIPLO_EVENTS
};

enum HurryTypes
{
	NO_HURRY = -1
};

enum LandmarkActionTypes
{
	NO_LANDMARK_ACTION = -1
};

enum LeaderheadAnimationTypes
{
	NO_LEADERHEAD_ANIM = -1,
	LEADERHEAD_ANIM_INTRO = 1,
	LEADERHEAD_ANIM_NEUTRAL_HELLO,
	LEADERHEAD_ANIM_PEACEFUL,
	LEADERHEAD_ANIM_OPENING_GLOAT,
	LEADERHEAD_ANIM_DECLARE_WAR,
	LEADERHEAD_ANIM_ATTACKED,
	LEADERHEAD_ANIM_HATE_HELLO,
	LEADERHEAD_ANIM_DEFEATED,
	LEADERHEAD_ANIM_REQUEST,
	LEADERHEAD_ANIM_DEMAND,
	LEADERHEAD_ANIM_NEUTRAL_IDLE,
	LEADERHEAD_ANIM_HATE_IDLE,
	LEADERHEAD_ANIM_LETS_HEAR_IT = 15,
	LEADERHEAD_ANIM_YES = 30,
	LEADERHEAD_ANIM_NO,
	LEADERHEAD_ANIM_POSITIVE = 30,
	LEADERHEAD_ANIM_NEGATIVE,
	LEADERHEAD_ANIM_HATE_POSITIVE = 40,
	LEADERHEAD_ANIM_HATE_NEGATIVE,
	LEADERHEAD_ANIM_HATE_LETS_HEAR_IT,
	LEADERHEAD_ANIM_TPOSE
};

enum LeagueTypes
{
	NO_LEAGUE = -1
};

enum MarvelTypes
{
	NO_MARVEL = -1
};

enum NationalSecurityProjectTypes
{
	NO_NATIONAL_SECURITY_PROJECT = -1
};

enum OutpostRemovalMethod
{
	NO_REMOVAL_METHOD = -1,
	OUTPOST_CONVERTED,
	OUTPOST_DESTROYED,
	OUTPOST_DISBANDED
};

enum PersonalityTraitTypes
{
	NO_PERSONALITY_TRAIT = -1
};

enum PlayerOptionTypes
{
	NO_PLAYEROPTION = -1,
	PLAYEROPTION_WAIT_END_TURN,
	PLAYEROPTION_SHOW_FRIENDLY_MOVES,
	PLAYEROPTION_SHOW_ENEMY_MOVES,
	PLAYEROPTION_QUICK_MOVES,
	PLAYEROPTION_START_AUTOMATED,
	PLAYEROPTION_SAFE_AUTOMATION,
	PLAYEROPTION_NO_UNIT_CYCLING,
	PLAYEROPTION_LEAVE_FORESTS,
	PLAYEROPTION_MODDER_1,
	PLAYEROPTION_MODDER_2,
	PLAYEROPTION_MODDER_3,
	NUM_PLAYEROPTION_TYPES,
	PLAYEROPTION_WAIT_END_TURN_HASH = 4048108754,
	PLAYEROPTION_SHOW_FRIENDLY_MOVES_HASH = 3211663018,
	PLAYEROPTION_SHOW_ENEMY_MOVES_HASH = 2974675837,
	PLAYEROPTION_QUICK_MOVES_HASH = 2826910319,
	PLAYEROPTION_START_AUTOMATED_HASH = 2836633922,
	PLAYEROPTION_SAFE_AUTOMATION_HASH = 3990093488,
	PLAYEROPTION_NO_UNIT_CYCLING_HASH = 1197333339,
	PLAYEROPTION_LEAVE_FORESTS_HASH = 3018733474,
	PLAYEROPTION_MODDER_1_HASH = 3558949959,
	PLAYEROPTION_MODDER_2_HASH = 1294472701,
	PLAYEROPTION_MODDER_3_HASH = 976168299,
	PLAYEROPTION_QUICK_SELECTION_ADVANCE = 3752237080
};

enum ReactionTypes
{
	NO_REACTION = -1
};

enum ResolutionTypes
{
	NO_RESOLUTION = -1
};

enum SpacecraftTypes
{
	RANDOM_SPACECRAFT = -2,
	NO_SELECTED_SPACECRAFT
};

enum StrategicSiteCommandTypes
{
	NO_SITECOMMAND = -1,
	SITECOMMAND_RANGE_SRIKE
};

enum TaskTypes
{
	TASK_RAZE,
	TASK_UNRAZE,
	TASK_DISBAND,
	TASK_GIFT,
	TASK_SET_AUTOMATED_CITIZENS,
	TASK_SET_AUTOMATED_PRODUCTION,
	TASK_SET_EMPHASIZE,
	TASK_NO_AUTO_ASSIGN_SPECIALISTS,
	TASK_ADD_SPECIALIST,
	TASK_REMOVE_SPECIALIST,
	TASK_CHANGE_WORKING_PLOT,
	TASK_REMOVE_SLACKER,
	TASK_CLEAR_WORKING_OVERRIDE,
	TASK_HURRY,
	TASK_CLEAR_ORDERS,
	TASK_RALLY_PLOT,
	TASK_CLEAR_RALLY_PLOT,
	TASK_RANGED_ATTACK,
	TASK_CREATE_PUPPET,
	TASK_ANNEX_PUPPET,
	TASK_ATTACK_ORBITAL,
	NUM_TASK_TYPES
};

enum TradeConnectionType
{
	TRADE_CONNECTION_INTERNATIONAL,
	TRADE_CONNECTION_INTERNAL_CITY,
	TRADE_CONNECTION_OUTPOST,
	TRADE_CONNECTION_STATION,
	NUM_TRADE_CONNECTION_TYPES
};

enum UnitPassiveAbilityTypes
{
	NO_UNIT_PASSIVE_ABILITY = -1
};

enum UnitPerkTypes
{
	NO_PERK = -1
};

enum UnitTypes
{
	NO_UNIT = -1
};

enum UnitUpgradeMode
{
	UNITUPGRADE_ADD,
	UNITUPGRADE_REMOVE,
	UNITUPGRADE_IGNORE
};

enum UnitUpgradeTypes
{
	NO_UPGRADE = -1
};

enum FlavorTypes
{
	NO_FLAVOR = -1,
};

enum ActionSubTypes
{
	NO_ACTIONSUBTYPE = -1,
	ACTIONSUBTYPE_INTERFACEMODE,
	ACTIONSUBTYPE_COMMAND,
	ACTIONSUBTYPE_BUILD,
	ACTIONSUBTYPE_PROMOTION,
	ACTIONSUBTYPE_SPECIALIST,
	ACTIONSUBTYPE_CONTROL,
	ACTIONSUBTYPE_AUTOMATE,
	ACTIONSUBTYPE_MISSION,
	NUM_ACTIONSUBTYPES
};

enum ReplayMessageTypes
{
	NO_REPLAY_MESSAGE = -1,

	REPLAY_MESSAGE_MAJOR_EVENT,
	REPLAY_MESSAGE_CITY_FOUNDED,
	REPLAY_MESSAGE_PLOT_OWNER_CHANGE,
	REPLAY_MESSAGE_CITY_CAPTURED,
	REPLAY_MESSAGE_CITY_DESTROYED,
	REPLAY_MESSAGE_RELIGION_FOUNDED,
	REPLAY_MESSAGE_PANTHEON_FOUNDED,

	NUM_REPLAY_MESSAGE_TYPES
};

enum TechTypes
{
	NO_TECH = -1,
};

enum MissionTypes
{
	NO_MISSION = -1,
};

enum EntityEventTypes
{
	ENTITY_EVENT_NONE = -1,            //!< Invalid event
};

enum SlotStatus
{
	SS_OPEN,
	SS_COMPUTER,
	SS_CLOSED,
	SS_TAKEN,
	SS_OBSERVER,

	SS_MAX_SLOT_STATUS,
};

enum ColorTypes
{
	NO_COLOR = -1,
};

enum DirectionTypes
{
	NO_DIRECTION = -1,
	DIRECTION_NORTHEAST,
	DIRECTION_EAST,
	DIRECTION_SOUTHEAST,
	DIRECTION_SOUTHWEST,
	DIRECTION_WEST,
	DIRECTION_NORTHWEST,
	NUM_DIRECTION_TYPES,
	DIRECTION_NORTH = DIRECTION_NORTHEAST,
	DIRECTION_SOUTH = DIRECTION_SOUTHWEST,
	DIRECTION_NORTH_MASK = 1 << 0,
	DIRECTION_NORTHEAST_MASK = 1 << 1,
	DIRECTION_EAST_MASK = 1 << 2,
	DIRECTION_SOUTHEAST_MASK = 1 << 3,
	DIRECTION_SOUTH_MASK = 1 << 4,
	DIRECTION_SOUTHWEST_MASK = 1 << 5,
	DIRECTION_WEST_MASK = 1 << 6,
	DIRECTION_NORTHWEST_MASK = 1 << 7,
};

enum FlowDirectionTypes
{
	NO_FLOWDIRECTION = -1,
	FLOWDIRECTION_NORTH,
	FLOWDIRECTION_NORTHEAST,
	FLOWDIRECTION_SOUTHEAST,
	FLOWDIRECTION_SOUTH,
	FLOWDIRECTION_SOUTHWEST,
	FLOWDIRECTION_NORTHWEST,
	NUM_FLOWDIRECTION_TYPES,
	FLOWDIRECTION_NORTH_MASK = 1 << 0,
	FLOWDIRECTION_SOUTH_MASK = 1 << 1,
	FLOWDIRECTION_SOUTHEAST_MASK = 1 << 2,
	FLOWDIRECTION_NORTHWEST_MASK = 1 << 3,
	FLOWDIRECTION_SOUTHWEST_MASK = 1 << 4,
	FLOWDIRECTION_NORTHEAST_MASK = 1 << 5,
};

enum ResourceTypes
{
	NO_RESOURCE = -1,
};

enum ResourceUsageTypes
{
	RESOURCEUSAGE_BONUS,
	RESOURCEUSAGE_STRATEGIC,
	RESOURCEUSAGE_LUXURY,

	NUM_RESOURCEUSAGE_TYPES
};

enum TeamTypes
{
	NO_TEAM = -1,
};

enum ImprovementUsageTypes
{
	IMPROVEMENTUSAGE_BASIC,
	IMPROVEMENTUSAGE_LANDMARK,

	NUM_IMPROVEMENTUSAGE_TYPES
};

enum EraTypes
{
	NO_ERA = -1,
};

enum GameStateTypes
{
	GAMESTATE_ON,
	GAMESTATE_OVER,
	GAMESTATE_EXTENDED,
};

enum GameOptionTypes
{
	NO_GAMEOPTION = -1,
	// TODO: GameOptionTypes (remaining Beyond Earth values).
};

enum MultiplayerOptionTypes
{
	NO_MPOPTION = -1,

	MPOPTION_SIMULTANEOUS_TURNS,
	MPOPTION_TAKEOVER_AI,
	MPOPTION_SHUFFLE_TEAMS,
	MPOPTION_ANONYMOUS,

	NUM_MPOPTION_TYPES
};

enum HandicapTypes
{
	NO_HANDICAP = -1,
};

enum GameSpeedTypes
{
	NO_GAMESPEED = -1,
};

enum CitySizeTypes
{
	NO_CITYSIZE = -1,
	CITYSIZE_SMALL,
	CITYSIZE_MEDIUM,
	CITYSIZE_LARGE,
	NUM_CITYSIZE_TYPES
};

enum CalendarTypes
{
	NO_CALENDAR = -1,
	CALENDAR_DEFAULT,
	CALENDAR_BI_YEARLY,
	CALENDAR_YEARS,
	CALENDAR_TURNS,
	CALENDAR_SEASONS,
	CALENDAR_MONTHS,
	CALENDAR_WEEKS,
};

enum ClimateTypes { NO_CLIMATE = -1 };
enum SeaLevelTypes { NO_SEALEVEL = -1 };
enum TurnTimerTypes { NO_TURNTIMER = -1 };
enum WorldSizeTypes
{
	NO_WORLDSIZE = -1,
	WORLDSIZE_DUEL,
	WORLDSIZE_TINY,
	WORLDSIZE_SMALL,
	WORLDSIZE_STANDARD,
	WORLDSIZE_LARGE,
	WORLDSIZE_HUGE,
	WORLDSIZE_DEBUG,
	NUM_WORLDSIZE_TYPES
};
enum GameMode
{
	NO_GAMEMODE = -1,
	GAMEMODE_NORMAL,
	GAMEMODE_PITBOSS,
	NUM_GAMEMODES
};
enum StorageLocation
{
	STORAGE_LOCAL,
	STORAGE_STEAM_CLOUD,
	STORAGE_MEMORY
};
// TODO: PlanetTypes (remaining Beyond Earth values).
enum PlanetTypes { NO_PLANET = -1 };


enum FogOfWarModeTypes {FOGOFWARMODE_OFF, FOGOFWARMODE_UNEXPLORED, FOGOFWARMODE_NOVIS, NUM_FOGOFWARMODE_TYPES};
enum PlotTypes {NO_PLOT = -1, PLOT_MOUNTAIN, PLOT_CANYON, PLOT_HILLS, PLOT_LAND, PLOT_OCEAN, NUM_PLOT_TYPES};
enum HeroLandmarkTypes {NO_HERO_LANDMARK = -1};
enum GenericWorldAnchorTypes {NO_WORLD_ANCHOR = -1, WORLD_ANCHOR_SETTLER, WORLD_ANCHOR_WORKER, WORLD_ANCHOR_EXPLORER, NUM_WORLD_ANCHORS};
enum BuildTypes {NO_BUILD = -1, BUILD_DummyEnum_00, BUILD_DummyEnum_01, BUILD_DummyEnum_02, BUILD_DummyEnum_03, BUILD_DummyEnum_04, BUILD_DummyEnum_05, BUILD_DummyEnum_06, BUILD_DummyEnum_07, BUILD_DummyEnum_08, BUILD_DummyEnum_09, BUILD_DummyEnum_10, BUILD_DummyEnum_11, BUILD_DummyEnum_12, BUILD_DummyEnum_13, BUILD_DummyEnum_14, BUILD_DummyEnum_15, BUILD_DummyEnum_16, BUILD_DummyEnum_17, BUILD_DummyEnum_18, BUILD_DummyEnum_19, BUILD_DummyEnum_20, BUILD_DummyEnum_21, BUILD_DummyEnum_22, BUILD_DummyEnum_23, BUILD_DummyEnum_24, BUILD_DummyEnum_25, BUILD_DummyEnum_26, BUILD_DummyEnum_27, BUILD_DummyEnum_28, BUILD_DummyEnum_29, BUILD_DummyEnum_30, BUILD_DummyEnum_31, BUILD_DummyEnum_32, BUILD_DummyEnum_33, BUILD_DummyEnum_34, BUILD_DummyEnum_35, BUILD_DummyEnum_36, BUILD_DummyEnum_37, BUILD_DummyEnum_38, BUILD_DummyEnum_39, BUILD_DummyEnum_40, BUILD_DummyEnum_41, BUILD_DummyEnum_42, BUILD_DummyEnum_43, BUILD_DummyEnum_44, BUILD_DummyEnum_45, BUILD_DummyEnum_46, BUILD_DummyEnum_47, BUILD_DummyEnum_48, BUILD_DummyEnum_49, BUILD_DummyEnum_50, BUILD_DummyEnum_51, BUILD_DummyEnum_52, BUILD_DummyEnum_53, BUILD_DummyEnum_54, BUILD_DummyEnum_55, BUILD_DummyEnum_56, BUILD_DummyEnum_57, BUILD_DummyEnum_58, BUILD_DummyEnum_59, BUILD_DummyEnum_60, BUILD_DummyEnum_61, BUILD_DummyEnum_62, BUILD_DummyEnum_63, BUILD_DummyEnum_64, BUILD_DummyEnum_65, BUILD_DummyEnum_66, BUILD_DummyEnum_67, BUILD_DummyEnum_68, BUILD_DummyEnum_69, BUILD_DummyEnum_70, BUILD_DummyEnum_71, BUILD_DummyEnum_72, BUILD_DummyEnum_73, BUILD_DummyEnum_74, BUILD_DummyEnum_75, BUILD_DummyEnum_76, BUILD_DummyEnum_77, BUILD_DummyEnum_78, BUILD_DummyEnum_79, BUILD_DummyEnum_80, BUILD_DummyEnum_81, BUILD_DummyEnum_82, BUILD_DummyEnum_83, BUILD_DummyEnum_84, BUILD_DummyEnum_85, BUILD_DummyEnum_86, BUILD_DummyEnum_87, BUILD_DummyEnum_88, BUILD_DummyEnum_89, BUILD_DummyEnum_90, BUILD_DummyEnum_91, BUILD_DummyEnum_92, BUILD_DummyEnum_93, BUILD_DummyEnum_94, BUILD_DummyEnum_95, BUILD_DummyEnum_96, BUILD_DummyEnum_97, BUILD_DummyEnum_98, BUILD_DummyEnum_99, BUILD_DummyEnum_100, BUILD_DummyEnum_101, BUILD_DummyEnum_102, BUILD_DummyEnum_103, BUILD_DummyEnum_104, BUILD_DummyEnum_105, BUILD_DummyEnum_106, BUILD_DummyEnum_107, BUILD_DummyEnum_108, BUILD_DummyEnum_109, BUILD_DummyEnum_110, BUILD_DummyEnum_111, BUILD_DummyEnum_112, BUILD_DummyEnum_113, BUILD_DummyEnum_114, BUILD_DummyEnum_115, BUILD_DummyEnum_116, BUILD_DummyEnum_117, BUILD_DummyEnum_118, BUILD_DummyEnum_119, BUILD_DummyEnum_120, BUILD_DummyEnum_121, BUILD_DummyEnum_122, BUILD_DummyEnum_123, BUILD_DummyEnum_124, BUILD_DummyEnum_125, BUILD_DummyEnum_126, BUILD_DummyEnum_127, BUILD_DummyEnum_128, BUILD_DummyEnum_129};
enum TerrainTypes {NO_TERRAIN = -1, TERRAIN_GRASS, TERRAIN_PLAINS, TERRAIN_DESERT, TERRAIN_TUNDRA, TERRAIN_SNOW, TERRAIN_COAST, TERRAIN_OCEAN, TERRAIN_MOUNTAIN, TERRAIN_HILL, TERRAIN_CANYON, TERRAIN_TRENCH, NUM_TERRAIN_TYPES};
enum FeatureTypes {INVALID_FEATURE = -2, NO_FEATURE};
enum ImprovementTypes {NO_IMPROVEMENT = -1, IMPROVEMENT_DummyEnum_00, IMPROVEMENT_DummyEnum_01, IMPROVEMENT_DummyEnum_02, IMPROVEMENT_DummyEnum_03, IMPROVEMENT_DummyEnum_04, IMPROVEMENT_DummyEnum_05, IMPROVEMENT_DummyEnum_06, IMPROVEMENT_DummyEnum_07, IMPROVEMENT_DummyEnum_08, IMPROVEMENT_DummyEnum_09, IMPROVEMENT_DummyEnum_10, IMPROVEMENT_DummyEnum_11, IMPROVEMENT_DummyEnum_12, IMPROVEMENT_DummyEnum_13, IMPROVEMENT_DummyEnum_14, IMPROVEMENT_DummyEnum_15, IMPROVEMENT_DummyEnum_16, IMPROVEMENT_DummyEnum_17, IMPROVEMENT_DummyEnum_18, IMPROVEMENT_DummyEnum_19, IMPROVEMENT_DummyEnum_20, IMPROVEMENT_DummyEnum_21, IMPROVEMENT_DummyEnum_22, IMPROVEMENT_DummyEnum_23, IMPROVEMENT_DummyEnum_24, IMPROVEMENT_DummyEnum_25, IMPROVEMENT_DummyEnum_26, IMPROVEMENT_DummyEnum_27, IMPROVEMENT_DummyEnum_28, IMPROVEMENT_DummyEnum_29, IMPROVEMENT_DummyEnum_30, IMPROVEMENT_DummyEnum_31, IMPROVEMENT_DummyEnum_32, IMPROVEMENT_DummyEnum_33, IMPROVEMENT_DummyEnum_34, IMPROVEMENT_DummyEnum_35, IMPROVEMENT_DummyEnum_36, IMPROVEMENT_DummyEnum_37, IMPROVEMENT_DummyEnum_38, IMPROVEMENT_DummyEnum_39, IMPROVEMENT_DummyEnum_40, IMPROVEMENT_DummyEnum_41, IMPROVEMENT_DummyEnum_42, IMPROVEMENT_DummyEnum_43, IMPROVEMENT_DummyEnum_44, IMPROVEMENT_DummyEnum_45, IMPROVEMENT_DummyEnum_46, IMPROVEMENT_DummyEnum_47, IMPROVEMENT_DummyEnum_48, IMPROVEMENT_DummyEnum_49, IMPROVEMENT_DummyEnum_50, IMPROVEMENT_DummyEnum_51, IMPROVEMENT_DummyEnum_52, IMPROVEMENT_DummyEnum_53, IMPROVEMENT_DummyEnum_54, IMPROVEMENT_DummyEnum_55, IMPROVEMENT_DummyEnum_56, IMPROVEMENT_DummyEnum_57, IMPROVEMENT_DummyEnum_58, IMPROVEMENT_DummyEnum_59, IMPROVEMENT_DummyEnum_60, IMPROVEMENT_DummyEnum_61, IMPROVEMENT_DummyEnum_62, IMPROVEMENT_DummyEnum_63, IMPROVEMENT_DummyEnum_64, IMPROVEMENT_DummyEnum_65, IMPROVEMENT_DummyEnum_66, IMPROVEMENT_DummyEnum_67, IMPROVEMENT_DummyEnum_68, IMPROVEMENT_DummyEnum_69, IMPROVEMENT_DummyEnum_70, IMPROVEMENT_DummyEnum_71, IMPROVEMENT_DummyEnum_72, IMPROVEMENT_DummyEnum_73, IMPROVEMENT_DummyEnum_74, IMPROVEMENT_DummyEnum_75, IMPROVEMENT_DummyEnum_76, IMPROVEMENT_DummyEnum_77, IMPROVEMENT_DummyEnum_78, IMPROVEMENT_DummyEnum_79, IMPROVEMENT_DummyEnum_80, IMPROVEMENT_DummyEnum_81, IMPROVEMENT_DummyEnum_82, IMPROVEMENT_DummyEnum_83, IMPROVEMENT_DummyEnum_84, IMPROVEMENT_DummyEnum_85, IMPROVEMENT_DummyEnum_86, IMPROVEMENT_DummyEnum_87, IMPROVEMENT_DummyEnum_88, IMPROVEMENT_DummyEnum_89, IMPROVEMENT_DummyEnum_90, IMPROVEMENT_DummyEnum_91, IMPROVEMENT_DummyEnum_92, IMPROVEMENT_DummyEnum_93, IMPROVEMENT_DummyEnum_94, IMPROVEMENT_DummyEnum_95, IMPROVEMENT_DummyEnum_96, IMPROVEMENT_DummyEnum_97, IMPROVEMENT_DummyEnum_98, IMPROVEMENT_DummyEnum_99, IMPROVEMENT_DummyEnum_100, IMPROVEMENT_DummyEnum_101, IMPROVEMENT_DummyEnum_102, IMPROVEMENT_DummyEnum_103, IMPROVEMENT_DummyEnum_104, IMPROVEMENT_DummyEnum_105, IMPROVEMENT_DummyEnum_106, IMPROVEMENT_DummyEnum_107, IMPROVEMENT_DummyEnum_108, IMPROVEMENT_DummyEnum_109, IMPROVEMENT_DummyEnum_110, IMPROVEMENT_DummyEnum_111, IMPROVEMENT_DummyEnum_112, IMPROVEMENT_DummyEnum_113, IMPROVEMENT_DummyEnum_114, IMPROVEMENT_DummyEnum_115, IMPROVEMENT_DummyEnum_116, IMPROVEMENT_DummyEnum_117, IMPROVEMENT_DummyEnum_118, IMPROVEMENT_DummyEnum_119, IMPROVEMENT_DummyEnum_120, IMPROVEMENT_DummyEnum_121, IMPROVEMENT_DummyEnum_122, IMPROVEMENT_DummyEnum_123, IMPROVEMENT_DummyEnum_124, IMPROVEMENT_DummyEnum_125, IMPROVEMENT_DummyEnum_126, IMPROVEMENT_DummyEnum_127, IMPROVEMENT_DummyEnum_128, IMPROVEMENT_DummyEnum_129};
enum RouteTypes {NO_ROUTE = -1, ROUTE_ROAD, ROUTE_MAGRAIL, NUM_ROUTE_TYPES};
enum CovertOperationTypes {NO_OPERATION = -1};
enum OrderTypes {NO_ORDER = -1, ORDER_TRAIN, ORDER_CONSTRUCT, ORDER_CREATE, ORDER_PREPARE, ORDER_MAINTAIN, NUM_ORDER_TYPES};
enum CityTaskResult {TASK_ABORTED, TASK_COMPLETED, TASK_QUEUED};

#endif // CVENUMS_H
